package layout

import (
	"fmt"

	"github.com/abdul-hamid-achik/tuimark/internal/ir"
)

// The geometry of the version="2" tabs, hints, and layout: grid (SPEC
// §6.10.4, §6.12, §11.7). Tab labels and hint items are generated by the
// host before layout (SPEC §18 steps 3 and 5); layout only decides which
// of them are laid out and where. Everything here is integer cell
// arithmetic, in one measure pass and one allocation pass.

// SparkShown returns the shown values of a sparkline's content box (SPEC
// §6.11, §6.15): the last W = b.Content.W elements of b.Series, right
// aligned (column j shows element len − W + j when that index is ≥ 0). It
// is used both by paint (which of them is a number decides whether the
// sparkline paints anything) and by internal/host's scale grouping
// (v0.3b), so both read exactly the same window.
func SparkShown(b *Box) []float64 {
	n, w := len(b.Series), b.Content.W
	if n == 0 || w <= 0 {
		return nil
	}
	out := make([]float64, 0, w)
	for j := max(0, w-n); j < w; j++ {
		out = append(out, b.Series[n-w+j])
	}
	return out
}

// tabParts returns the label boxes of tabs t (its children with
// RoleTabLabel, in document order) and its active tab (its child of kind
// tab), or nil when no tab is visible.
func tabParts(t *Box) (labels []*Box, tab *Box) {
	for _, c := range t.Children {
		switch {
		case c.Role == RoleTabLabel:
			labels = append(labels, c)
		case c.Kind == "tab" && tab == nil:
			tab = c
		}
	}
	return labels, tab
}

// markWidth is m of SPEC §6.10.4: the width of a tabs' mark, 0 without
// one (a mark that is not 1 or 2 columns wide is V018 and counts as none).
func markWidth(t *Box) int {
	if w := Width(t.Mark); w >= 1 && w <= 2 {
		return w
	}
	return 0
}

// tabWidths returns W1 and W2 of SPEC §6.10.4 for the labels of tabs t:
// Σ (m + width(L(t))) + g·(n − 1), and the same with S(t). Labels are
// always laid out side by side, so g is the tabs' column-gap in a
// version="3" document (SPEC §10.2, v0.3b).
func tabWidths(t *Box, labels []*Box, v3 bool) (w1, w2 int) {
	n := len(labels)
	if n == 0 {
		return 0, 0
	}
	m, g := markWidth(t), columnGap(t.Style, v3)
	w1, w2 = g*(n-1), g*(n-1)
	for _, l := range labels {
		w1 += m + Width(l.Full)
		w2 += m + Width(l.Short)
	}
	return clampCells(w1), clampCells(w2)
}

// tabsIntrinsic is the content-driven size of tabs t without its border
// and padding (SPEC §6.10.4 item 7): across, the larger of W1 and the
// active tab's intrinsic width; down, the strip row plus the active tab's
// intrinsic height (just the strip row without an active tab). avail is
// the content size on the other axis.
func (e *Engine) tabsIntrinsic(t *Box, horizontal bool, avail int) int {
	labels, tab := tabParts(t)
	if horizontal {
		w1, _ := tabWidths(t, labels, e.V3)
		if tab != nil {
			w1 = max(w1, e.intrinsic(tab, true, max(0, avail-1)))
		}
		return w1
	}
	if tab == nil {
		return 1
	}
	return clampCells(1 + e.intrinsic(tab, false, avail))
}

// tabsLayout lays out tabs t inside its content box C (SPEC §6.10.4): the
// labels of its visible tabs on the first row, in tier 1 (every label,
// full text) when W1 ≤ C, tier 2 (every label, short text) when W2 ≤ C,
// else tier 3 (the active tab's label alone, "‹ L ›", "‹ S ›", or that
// truncated); every label reserves m columns for the mark in front of its
// text, so positions do not depend on the active tab. Labels left out are
// not laid out. The active tab is laid out below the strip over the rest
// of the content box, whatever its own sizes say; its border, padding,
// gap, layout, and align apply. clip is t's clip inside its content box.
func (e *Engine) tabsLayout(t *Box, clip Rect) {
	c := t.Content
	labels, tab := tabParts(t)
	if len(labels) > 0 {
		m, g := markWidth(t), columnGap(t.Style, e.V3)
		w1, w2 := tabWidths(t, labels, e.V3)
		switch {
		case w1 <= c.W || w2 <= c.W:
			x := c.X
			for _, l := range labels {
				l.Text = l.Full
				if w1 > c.W {
					l.Text = l.Short
				}
				w := m + Width(l.Text)
				placeLabel(l, Rect{x, c.Y, w, 1}, m, clip)
				x += w + g
			}
		default:
			for _, l := range labels {
				if !l.Selected {
					continue
				}
				text := "‹ " + l.Full + " ›"
				if m+Width(text) > c.W {
					text = "‹ " + l.Short + " ›"
					if m+Width(text) > c.W {
						text = Truncate(text, max(0, c.W-m))
					}
				}
				l.Text = text
				placeLabel(l, Rect{c.X, c.Y, m + Width(text), 1}, m, clip)
			}
		}
	}
	if tab != nil {
		e.place(tab, Rect{c.X, c.Y + 1, c.W, max(0, c.H-1)}, clip)
	}
}

// placeLabel gives a tab label its rect r, its mark slot of m columns in
// front of its text, and its clip inside the tabs' content box clip. A
// label ignores its own sizes, spacing, and border (it is Fixed).
func placeLabel(l *Box, r Rect, m int, clip Rect) {
	l.X, l.Y, l.W, l.H = r.X, r.Y, r.W, r.H
	l.Laid = true
	l.Clip = clip.Intersect(l.Outer())
	l.Chan = m
	l.Content = Rect{X: l.X + m, Y: l.Y, W: max(0, l.W-m), H: l.H}
}

// hintItemSize is the size of a hint item row across its hints' main
// axis (SPEC §6.12): width(keycap) + the row's gap + width(label). The
// keycap and label are always laid out side by side, so the gap is the
// item's column-gap in a version="3" document (SPEC §10.2, v0.3b).
func hintItemSize(it *Box, v3 bool) int {
	if len(it.Children) < 2 {
		return 0
	}
	return clampCells(Width(it.Children[0].Text) + columnGap(it.Style, v3) + Width(it.Children[1].Text))
}

// hintsColumn reports whether hints h places its items down (layout:
// column); otherwise, row being the default, across (grid is ignored).
func hintsColumn(h *Box) bool { return h.Style.Layout == "column" }

// hintsIntrinsic is the content-driven size of hints h without its border
// and padding (SPEC §6.12): under layout: row, every item's width plus
// the gaps across and one row down; under layout: column, the widest item
// across and one row per item plus the gaps down. Every item counts,
// whether it fits or not. The items' own main-axis gap is hints' g of
// SPEC §11.7's letters: column-gap under layout: row, row-gap under
// layout: column (v0.3b).
func hintsIntrinsic(h *Box, horizontal, v3 bool) int {
	n := len(h.Children)
	col := hintsColumn(h)
	if horizontal == col {
		// Across the items: the widest one (column) or one row (row).
		if !col {
			return 1
		}
		w := 0
		for _, it := range h.Children {
			w = max(w, hintItemSize(it, v3))
		}
		return w
	}
	if n == 0 {
		return 0
	}
	v := mainGap(h.Style, v3, !col) * (n - 1)
	for _, it := range h.Children {
		if col {
			v++
		} else {
			v += hintItemSize(it, v3)
		}
	}
	return clampCells(v)
}

// hintsLayout places the items of hints h one after another along its
// main axis, separated by its gap, each at its own size (SPEC §6.12): the
// first item that does not fit entirely in what is left of the content
// box on that axis, and every item after it, is not laid out. Inside an
// item, the keycap text comes first, then the row's gap, then the label.
func (e *Engine) hintsLayout(h *Box, clip Rect) {
	c := h.Content
	col := hintsColumn(h)
	extent := c.W
	if col {
		extent = c.H
	}
	pos := 0
	mg := mainGap(h.Style, e.V3, !col)
	for _, it := range h.Children {
		w := hintItemSize(it, e.V3)
		size := w
		if col {
			size = 1
		}
		if pos+size > extent || len(it.Children) < 2 {
			return
		}
		r := Rect{c.X + pos, c.Y, w, 1}
		if col {
			r = Rect{c.X, c.Y + pos, w, 1}
		}
		placeFixed(it, r, clip)
		key, label := it.Children[0], it.Children[1]
		kw := Width(key.Text)
		placeFixed(key, Rect{r.X, r.Y, kw, 1}, it.Clip)
		lx := r.X + kw + columnGap(it.Style, e.V3)
		placeFixed(label, Rect{lx, r.Y, Width(label.Text), 1}, it.Clip)
		pos += size + mg
	}
}

// placeFixed gives a generated box its rect r, which is also its content
// box, clipped by clip.
func placeFixed(b *Box, r Rect, clip Rect) {
	b.X, b.Y, b.W, b.H = r.X, r.Y, max(0, r.W), max(0, r.H)
	b.Laid = true
	b.Clip = clip.Intersect(b.Outer())
	b.Content = b.Outer()
}

// gridColumns returns the column count n and the column widths of a grid
// whose content width is wc (SPEC §11.7 items 1-2): n = K without
// grid-min-width, else clamp(floor((wc + g) / (M + g)), 1, K); then the
// §11.4 split of n children of 1fr with gap g: columns 0 to n − 2 get
// floor(remain / n) and the last gets the rest, remain = max(0, wc −
// g·(n − 1)). g is the grid's column-gap in a version="3" document (SPEC
// §11.7, v0.3b).
func gridColumns(b *Box, wc int, v3 bool) (n int, widths []int) {
	k := min(max(b.Style.GridColumns, 1), 12)
	g := columnGap(b.Style, v3)
	n = k
	if m := b.Style.GridMinWidth; m > 0 {
		n = min(max((max(wc, 0)+g)/(m+g), 1), k)
	}
	remain := max(0, wc-g*(n-1))
	widths = make([]int, n)
	for j := 0; j < n-1; j++ {
		widths[j] = remain / n
	}
	widths[n-1] = remain - (remain/n)*(n-1)
	return n, widths
}

// gridChildHeight is a grid child's height in its row, margins included
// (SPEC §11.7 item 4): its height when that is a cell count, else its
// intrinsic height at its column's width (an fr or % height is auto
// here), clamped by min-height and max-height.
func (e *Engine) gridChildHeight(k *Box, colW int) int {
	ms, me := margins(k, false)
	cs, ce := margins(k, true)
	var h int
	if s := k.Style.Height; s.Kind == ir.Cell {
		h = cells(s.N)
	} else {
		h = e.intrinsic(k, false, max(0, colW-cs-ce))
	}
	return clampCells(clampAxis(k, false, h, -1) + ms + me)
}

// gridRows returns the height of each grid row (the largest height of its
// children, SPEC §11.7 item 4) for kids in n columns of the given widths.
func (e *Engine) gridRows(kids []*Box, n int, widths []int) []int {
	rows := make([]int, (len(kids)+n-1)/n)
	for i, k := range kids {
		r := i / n
		rows[r] = max(rows[r], e.gridChildHeight(k, widths[i%n]))
	}
	return rows
}

// gridWc is the content width a grid lays out in: area's width, what the
// left and right docks leave of its content box; when b scrolls on x, its
// content-box width minus what those docks took from its content extent
// (SPEC §11.7 item 7).
func gridWc(b *Box, area Rect) int {
	if b.scrollsOn(true) {
		return max(0, b.Content.W-(b.ContentW-area.W))
	}
	return area.W
}

// gridIntrinsic is the content-driven size of grid container b's in-flow
// children kids (SPEC §11.7 item 6): down, the row heights plus the gaps
// between rows at the columns avail (the content width the left and right
// docks leave) gives; across, n'·w + g·(n' − 1), with n' = K without
// grid-min-width (item 1 then lays out K columns, whatever the number of
// children), else min(K, the number of children), at least 1, and w the
// grid-min-width, else the widest child. g is column-gap across, row-gap
// down, in a version="3" document (SPEC §11.7, v0.3b).
func (e *Engine) gridIntrinsic(b *Box, kids []*Box, horizontal bool, avail int) int {
	if horizontal {
		g := columnGap(b.Style, e.V3)
		k := min(max(b.Style.GridColumns, 1), 12)
		n := k
		if b.Style.GridMinWidth > 0 {
			n = max(1, min(k, len(kids)))
		}
		w := b.Style.GridMinWidth
		if w <= 0 {
			w = 0
			for _, c := range kids {
				cs, ce := margins(c, true)
				w = max(w, e.intrinsic(c, true, 0)+cs+ce)
			}
		}
		return clampCells(n*w + g*(n-1))
	}
	if len(kids) == 0 {
		return 0
	}
	n, widths := gridColumns(b, avail, e.V3)
	rows := e.gridRows(kids, n, widths)
	v := rowGap(b.Style, e.V3) * (len(rows) - 1)
	for _, h := range rows {
		v += h
	}
	return clampCells(v)
}

// grid places the in-flow children kids of grid container b inside area
// (SPEC §11.7): child i in row floor(i / n), column i mod n, as wide as
// its column minus its margins (its width, min-width, max-width, and
// flex are ignored: L007 when the document wrote one, and for an fr or %
// height, which is auto here); rows as tall as their tallest child,
// separated by the gap; align places a shorter child in its row (stretch
// by default; justify does not apply). The columns are g apart (its
// column-gap in a version="3" document) and the rows g apart too, but
// with row-gap there (SPEC §11.7, v0.3b).
func (e *Engine) grid(b *Box, kids []*Box, area Rect, clip Rect) {
	cg, rg := columnGap(b.Style, e.V3), rowGap(b.Style, e.V3)
	n, widths := gridColumns(b, gridWc(b, area), e.V3)
	xs := make([]int, n)
	x := area.X
	for j := range widths {
		xs[j] = x
		x += widths[j] + cg
	}
	for _, k := range kids {
		if what := gridIgnored(k); what != "" {
			e.report(k, ir.Warning, "L007", "%s is ignored in a layout: grid container (%s); its column sets its width and its content its height", what, describe(b))
		}
	}
	rows := e.gridRows(kids, n, widths)
	y := area.Y
	for r, h := range rows {
		for j := 0; j < n; j++ {
			i := r*n + j
			if i >= len(kids) {
				break
			}
			k := kids[i]
			ms, me := margins(k, false)
			cs, ce := margins(k, true)
			own := e.gridChildHeight(k, widths[j])
			boxH, off := max(0, h-ms-me), 0
			switch b.Style.Align {
			case "start", "center", "end":
				boxH = max(0, own-ms-me)
				switch b.Style.Align {
				case "center":
					off = max(0, (h-own)/2)
				case "end":
					off = max(0, h-own)
				}
			}
			e.place(k, Rect{xs[j] + cs, y + off + ms, max(0, widths[j]-cs-ce), boxH}, clip)
		}
		y += h + rg
	}
}

// gridIgnored names the sizes a grid child k has that the grid ignores
// and the document wrote (a presentational attribute, author CSS, or
// style=""): width, min-width, max-width, flex, and an fr or % height
// (SPEC §11.7 items 3-4, L007). The built-in sheet's col/row 1fr and
// spacer flex: 1 are ignored silently. "" when there is none.
func gridIgnored(k *Box) string {
	st := k.Style
	switch {
	case st.Width.Kind != ir.Unset && !st.WidthUA:
		return fmt.Sprintf("width: %s", st.Width)
	case st.MinW.Kind != ir.Unset:
		return fmt.Sprintf("min-width: %s", st.MinW)
	case st.MaxW.Kind != ir.Unset:
		return fmt.Sprintf("max-width: %s", st.MaxW)
	case st.FlexSet && !st.FlexUA:
		return "flex: " + st.FlexLit
	case (st.Height.Kind == ir.Fr || st.Height.Kind == ir.Pct) && !st.HeightUA:
		return fmt.Sprintf("height: %s", st.Height)
	}
	return ""
}
