// Package uniwidth measures text the way Tuimark lays it out and paints it
// (SPEC v0.2 §11.5.1): as a sequence of extended grapheme clusters (UAX #29,
// segmented by github.com/rivo/uniseg, Unicode 15.0.0), each 0, 1, or 2
// columns wide by a Tuimark-owned width function.
//
// The width function never depends on the locale, on the terminal, or on
// uniseg.EastAsianAmbiguousWidth, a process-wide variable that another
// package in the same binary may change: East Asian Ambiguous code points
// are always 1 column (ADR 0002, SPEC MUST NOT 9). The package never reads
// or writes that variable either: uniseg reads it only while measuring an
// East Asian Ambiguous code point, so Next hands uniseg a stand-in with the
// same Grapheme_Cluster_Break property in its place. Rendering is
// therefore not a data race with another goroutine that sets it. The
// tables (tables.go) are generated by gen.go.
package uniwidth

//go:generate go run gen.go

import (
	"unicode/utf8"

	"github.com/rivo/uniseg"
)

type span struct{ lo, hi rune }

func in(table []span, r rune) bool {
	lo, hi := 0, len(table)
	for lo < hi {
		m := int(uint(lo+hi) >> 1)
		switch {
		case r < table[m].lo:
			hi = m
		case r > table[m].hi:
			lo = m + 1
		default:
			return true
		}
	}
	return false
}

// RuneWidth is rw(r) of SPEC §11.5.1: 0 for Grapheme_Cluster_Break Control,
// CR, LF, Extend, and ZWJ; 2 for Regional_Indicator, Extended_Pictographic
// with Emoji_Presentation or with East_Asian_Width W or F, U+2E3A, U+2E3B,
// and East_Asian_Width W or F; 1 otherwise, East_Asian_Width Ambiguous
// included.
func RuneWidth(r rune) int {
	if r < 0x7F {
		if r >= 0x20 {
			return 1
		}
		return 0
	}
	if in(zeroWidth, r) {
		return 0
	}
	if in(doubleWidth, r) {
		return 2
	}
	return 1
}

func regionalIndicator(r rune) bool { return r >= 0x1F1E6 && r <= 0x1F1FF }

// hangulL reports Grapheme_Cluster_Break=L (Hangul leading jamo).
func hangulL(r rune) bool { return (r >= 0x1100 && r <= 0x115F) || (r >= 0xA960 && r <= 0xA97C) }

// ClusterWidth is W(c) of SPEC §11.5.1 for one grapheme cluster c: 0, 1, or
// 2. A cluster led by an Extended_Pictographic code point is the lead's
// width, set to 1 by a later U+FE0E and to 2 by a later U+FE0F; one led by a
// Regional_Indicator or a Hangul leading jamo is its lead's width; any other
// is the sum of its code points' widths. The result is capped at 2.
func ClusterWidth(c string) int {
	if c == "" {
		return 0
	}
	r0, n := utf8.DecodeRuneInString(c)
	w := RuneWidth(r0)
	if n == len(c) {
		return min(w, 2)
	}
	switch {
	case r0 >= 0xA9 && in(pictographic, r0):
		for _, r := range c[n:] {
			switch r {
			case 0xFE0E:
				w = 1
			case 0xFE0F:
				w = 2
			}
		}
	case regionalIndicator(r0) || hangulL(r0):
	default:
		for _, r := range c[n:] {
			w += RuneWidth(r)
		}
	}
	return min(w, 2)
}

// Complex reports whether cluster c, of width w, is a complex cluster (SPEC
// §11.5.1): 2 columns wide or more than one code point. Complex clusters set
// the dump's "wide" flag and get CHA re-positioning in Run.
func Complex(c string, w int) bool {
	if w == 2 {
		return true
	}
	_, n := utf8.DecodeRuneInString(c)
	return n < len(c)
}

// printable reports whether b is a printable ASCII byte. Such a byte is a
// whole cluster of width 1 unless a non-ASCII code point follows it (an
// Extend, ZWJ, or SpacingMark attaches to it).
func printable(b byte) bool { return b >= 0x20 && b < 0x7F }

// Joiner reports whether r's Grapheme_Cluster_Break is neither Other nor
// Control, CR, or LF: Prepend, Extend, ZWJ, SpacingMark,
// Regional_Indicator, Hangul L, V, T, LV, or LVT, or Extended_Pictographic.
// Apart from CR LF, two adjacent code points can be in one cluster only
// when one of them is a joiner (UAX #29), so strings with neither joiners
// nor CR LF pairs segment one code point per cluster however they are
// concatenated.
func Joiner(r rune) bool { return r >= 0xA9 && in(joiner, r) }

// other reports whether r's Grapheme_Cluster_Break is Other (an invalid
// byte decodes to U+FFFD, which is Other).
func other(r rune) bool { return !in(zeroWidth, r) && !Joiner(r) }

// simple returns the byte length and width of the first cluster of a
// non-empty s when it is found without uniseg, and whether it was. The
// segmentation state after it is the fresh one (-1).
func simple(s string) (n, width int, ok bool) {
	if printable(s[0]) && (len(s) == 1 || s[1] < 0x80) {
		// An ASCII boundary follows: the next cluster starts afresh.
		return 1, 1, true
	}
	// A cluster that starts with an Other code point ends before the next
	// code point unless that one is Extend, ZWJ, or SpacingMark (UAX #29
	// GB9, GB9a; every other rule that joins needs a joiner first), and
	// the state after that boundary is the fresh one.
	r0, n0 := utf8.DecodeRuneInString(s)
	if !other(r0) {
		return 0, 0, false
	}
	if n0 < len(s) && s[n0] >= 0x80 { // no ASCII code point is a follower
		if r1, _ := utf8.DecodeRuneInString(s[n0:]); in(follower, r1) {
			return 0, 0, false
		}
	}
	return n0, min(RuneWidth(r0), 2), true
}

// Next returns the first grapheme cluster of s, the rest of s, the
// cluster's width, and the segmentation state to pass with the rest. Pass
// state -1 for the first call on a string; segmentation starts fresh for
// every string Tuimark measures (SPEC §11.5.1).
func Next(s string, state int) (cluster, rest string, width, newState int) {
	if s == "" {
		return "", "", 0, state
	}
	if n, w, ok := simple(s); ok {
		return s[:n], s[n:], w, -1
	}
	n, newState := firstCluster(s, state)
	return s[:n], s[n:], ClusterWidth(s[:n]), newState
}

// standIn[n] is the code point, n bytes long in UTF-8, that uniseg
// segments in place of an ambiguous code point n bytes long (for n = 1, an
// invalid byte, which decodes to U+FFFD). Like every ambiguous code point
// it has Grapheme_Cluster_Break Other, so the boundaries do not change,
// and uniseg measures it without reading EastAsianAmbiguousWidth. gen.go
// checks both.
var standIn = [5]string{1: "a", 2: "\u00A2", 3: "\u4E00", 4: "\U00020000"}

// standsIn reports whether r is in the ambiguous table: whether uniseg's
// width lookup for r reads EastAsianAmbiguousWidth, so that uniseg must
// segment a stand-in instead. The ranges checked first hold the whole
// table (TestAmbiguousTable checks it), so most scripts skip the search.
func standsIn(r rune) bool {
	switch {
	case r < 0xA1:
		return false
	case r <= 0x0451, r >= 0x2010 && r <= 0x324F, r >= 0xE000 && r <= 0xF8FF, r == 0xFFFD,
		r >= 0x1F100 && r <= 0x1F1AC, r >= 0xF0000:
		return in(ambiguous, r)
	}
	return false
}

// firstCluster returns the byte length of the first grapheme cluster of s,
// as uniseg v0.4.7 segments it, and the state to pass with the rest.
// uniseg reads EastAsianAmbiguousWidth whenever it measures an ambiguous
// code point, which this package must never make it do (SPEC §11.5.1), so
// each one is replaced by its stand-in before uniseg sees it. Only a
// window of s is copied: a boundary found inside the window is the
// boundary in s, because it depends only on the code points before it and
// the one after it.
func firstCluster(s string, state int) (n, newState int) {
	for _, limit := range [...]int{32, 256} {
		if n, newState, ok := firstClusterWithin(s, limit, state); ok {
			return n, newState
		}
	}
	n, newState, _ = firstClusterWithin(s, len(s), state)
	return n, newState
}

// firstClusterWithin segments the first cluster of the longest prefix of
// s made of whole code points that is at most limit bytes long (and at
// least one code point). ok reports whether that cluster is the first
// cluster of s: it ends before the prefix does, or the prefix is s.
func firstClusterWithin(s string, limit, state int) (n, newState int, ok bool) {
	m, stand := 0, false
	for m < len(s) {
		r, size := utf8.DecodeRuneInString(s[m:])
		if m > 0 && m+size > limit {
			break
		}
		stand = stand || standsIn(r)
		m += size
	}
	if !stand {
		c, _, _, st := uniseg.FirstGraphemeClusterInString(s[:m], state)
		return len(c), st, len(c) < m || m == len(s)
	}
	var buf [256]byte
	b := buf[:0]
	if m > len(buf) {
		b = make([]byte, 0, m)
	}
	for i := 0; i < m; {
		r, size := utf8.DecodeRuneInString(s[i:])
		if standsIn(r) {
			b = append(b, standIn[size]...)
		} else {
			b = append(b, s[i:i+size]...)
		}
		i += size
	}
	c, _, _, st := uniseg.FirstGraphemeCluster(b, state)
	return len(c), st, len(c) < m || m == len(s)
}

// segmenter walks the grapheme clusters of one string, like repeated
// calls of Next, and remembers where the next ambiguous code point is, so
// that the string is searched for them only once.
type segmenter struct {
	rest  string
	state int
	// amb is the offset in rest of its first ambiguous code point, or
	// len(rest) when it has none, or -1 when not known yet.
	amb int
}

func newSegmenter(s string) segmenter { return segmenter{rest: s, state: -1, amb: -1} }

// next returns the next cluster and its width; rest must not be empty.
func (g *segmenter) next() (cluster string, width int) {
	s := g.rest
	n, w, ok := simple(s)
	if ok {
		g.state = -1
	} else {
		if g.amb < 0 {
			g.amb = len(s)
			for i, r := range s {
				if standsIn(r) {
					g.amb = i
					break
				}
			}
		}
		ok = false
		if g.amb > 0 {
			// uniseg may see s up to the ambiguous code point as it is.
			c, _, _, st := uniseg.FirstGraphemeClusterInString(s[:g.amb], g.state)
			if ok = len(c) < g.amb || g.amb == len(s); ok {
				n, g.state = len(c), st
			}
		}
		if !ok {
			n, g.state = firstCluster(s, g.state)
		}
		w = ClusterWidth(s[:n])
	}
	g.rest = s[n:]
	if g.amb >= 0 {
		if g.amb -= n; g.amb < 0 {
			g.amb = -1
		}
	}
	return s[:n], w
}

// Each calls fn with every grapheme cluster of s and its width, in order,
// until fn returns false.
func Each(s string, fn func(cluster string, width int) bool) {
	for g := newSegmenter(s); g.rest != ""; {
		if !fn(g.next()) {
			return
		}
	}
}

// asciiPrintable reports whether every byte of s is printable ASCII, in
// which case every byte is a cluster of width 1.
func asciiPrintable(s string) bool {
	for i := 0; i < len(s); i++ {
		if !printable(s[i]) {
			return false
		}
	}
	return true
}

// Width is width(s) of SPEC §11.5.2: the sum of the widths of the grapheme
// clusters of s. It does not treat "\n" specially (a line feed is width 0).
func Width(s string) int {
	if asciiPrintable(s) {
		return len(s)
	}
	w := 0
	for g := newSegmenter(s); g.rest != ""; {
		_, cw := g.next()
		w += cw
	}
	return w
}

// Count returns the number of grapheme clusters of s.
func Count(s string) int {
	if asciiPrintable(s) {
		return len(s)
	}
	n := 0
	for g := newSegmenter(s); g.rest != ""; g.next() {
		n++
	}
	return n
}

// Split returns the grapheme clusters of s, in order.
func Split(s string) []string {
	var out []string
	Each(s, func(c string, _ int) bool {
		out = append(out, c)
		return true
	})
	return out
}

// Prefix returns the byte length of the longest prefix of whole grapheme
// clusters of s whose width is at most n, and that width. Zero-width
// clusters right after the prefix belong to it.
func Prefix(s string, n int) (bytes, width int) {
	if n <= 0 {
		return 0, 0
	}
	if asciiPrintable(s) {
		k := min(len(s), n)
		return k, k
	}
	for g := newSegmenter(s); g.rest != ""; {
		c, cw := g.next()
		if width+cw > n {
			break
		}
		bytes += len(c)
		width += cw
	}
	return bytes, width
}
